// Auto-generated by the postman-to-k6 converter

import "../libs/shim/core.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };


const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});



export default function() {
  group("user_api", function() {
    postman[Request]({
      name: "get_user",
      id: "094e7ce6-f300-48ee-8d7d-211728667aac",
      method: "GET",
      address: "http://127.0.0.1:8080/api/user",
      headers: {
        authentication_token:
          "WyJjNTA3OWYzYWJkMjg0NTM4YWJiMDQxOTExMzhmYzNiNCJd.Y76bWQ.hai-hLa7DwPVX84rPlMNxVL31_g"
      }
    });

    postman[Request]({
      name: "login/include_auth_token",
      id: "5af16de7-2e79-438d-82b7-0cd79284fe77",
      method: "POST",
      address: "http://127.0.0.1:8080/login?include_auth_token",
      data: '{\r"email": "smk@gmail.com",\r  "password":"1212"\r}'
    });

    postman[Request]({
      name: "New Request",
      id: "37ac91eb-07c7-42ec-ab06-4b48b1c3ceb9",
      method: "GET",
      address: "http:///"
    });

    postman[Request]({
      name: "New Request",
      id: "29391cc6-cf90-41a9-9a60-f03a9df44f3e",
      method: "GET",
      address: "http:///"
    });
  });



  group("list_api", function() {
    postman[Request]({
      name: "get_list",
      id: "8997157c-0af3-459c-a55a-a104cc75c810",
      method: "GET",
      address: "http://127.0.0.1:8080/api/list?list_id=3",
      headers: {
        authentication_token:
          "WyJjNTA3OWYzYWJkMjg0NTM4YWJiMDQxOTExMzhmYzNiNCJd.Y76bWQ.hai-hLa7DwPVX84rPlMNxVL31_g"
      }
    });

    postman[Request]({
      name: "create_list",
      id: "df42a9e9-bf8d-4b36-8d9e-e518c6bdcd12",
      method: "POST",
      address: "http://127.0.0.1:8080/api/list?list_name=cv&description=vc",
      headers: {
        authentication_token:
          " WyJjNTA3OWYzYWJkMjg0NTM4YWJiMDQxOTExMzhmYzNiNCJd.Y76jgQ.RsQSfW1shs9GuroOXSQnlYsv3mA"
      }
    });
  });




  group("card_api", function() {
    postman[Request]({
      name: "get_card",
      id: "98137e19-fdcd-45d6-9e9e-90545424eedb",
      method: "GET",
      address: "http://127.0.0.1:8080/api/card?card_id=5",
      headers: {
        authentication_token:
          " WyJjNTA3OWYzYWJkMjg0NTM4YWJiMDQxOTExMzhmYzNiNCJd.Y76jgQ.RsQSfW1shs9GuroOXSQnlYsv3mA"
      }
    });

    postman[Request]({
      name: "create_card",
      id: "14cb83d6-c1a5-40c8-889c-9e758f76ce38",
      method: "POST",
      address:
        "http://127.0.0.1:8080/api/card?card_title=unit5&content=transactions&deadline=2023-04-01&percent=25&list_id=3",
      headers: {
        authentication_token:
          " WyJjNTA3OWYzYWJkMjg0NTM4YWJiMDQxOTExMzhmYzNiNCJd.Y76jgQ.RsQSfW1shs9GuroOXSQnlYsv3mA"
      }
    });
  });

  group("summary", function() {
    postman[Request]({
      name: "task_check",
      id: "473b5eaf-e388-4c64-b904-cd79555fd2a0",
      method: "GET",
      address: "http:///"
    });
  });
}
